### PR TITLE
Ert workflow job

### PR DESCRIPTION
**Pull request by perolavsvendsen**
Solve #55 

Attempting to expand the current usage of script in ERT `FORWARD_JOB` to also be used as an ERT `WORKFLOW_JOB`. End result should be that the `SUMO_UPLOAD` can be called from both FORWARD_JOB and WORKLOW in the ERT context.

### CODE REVIEW

**Comment by perolavsvendsen** [comment]
Needs to be tested to confirm that both contexts are in fact still working, also in the wild.

**Comment by perolavsvendsen** [comment]
Tested with `Drogon` using a komodo-environment. Confirmed that the FORWARD_JOB context still works and that the workflow context is now also working without having to define and install the workflow job locally.

**Comment by oihaa** [comment]
A few of the method added have specified return type. You should make a choice.

**Comment by oihaa** [comment]
In setup.py there are two entries for ert, one with hyphens, which you already have renamed, and one CameCase. Please make a choice. But more relevant are they both needed?

There are now two ways to inject an item into ert. By adding a new file in the config_jobs folder, which was the original case. And by creating the item in Python. One way would sufficient.

**Comment by oihaa** [comment]
You need to increase the version number to your choice, if you want to add the updated functionality in Komodo.

**Comment by perolavsvendsen** [comment]
> There are now two ways to inject an item into ert. By adding a new file in the config_jobs folder, which was the original case. And by creating the item in Python. One way would sufficient.

Unkown territory, but I believe there are differences between `forward_job` and `workflow_job` implementations.

**Comment by perolavsvendsen** [comment]
As far as I can find from testing through komodoenv, both entry points are not needed. So I have removed one.

I have tried to look around a bit on other similar implementations. Example: https://github.com/equinor/subscript/blob/master/src/subscript/fmuobs/fmuobs.py

**Comment by oihaa** [comment]
Can src/jobs/ folder be deleted. There are no longer references from setup.py.

**Comment by perolavsvendsen** [comment]
> Can src/jobs/ folder be deleted. There are no longer references from setup.py.

Testing with a clean environment it seems like both are needed to cover both forward_job and workflow_job contexts

**Review by oihaa — APPROVED** [review]

**Comment by perolavsvendsen** [comment]
Not needed: https://github.com/perolavsvendsen/fmu-sumo/blob/17871496e1613162c48ed17c865cf9c670beafb1/src/jobs/hook_implementations/jobs.py#L27

**Pull request merged**
